### PR TITLE
fix: changed the blog guide

### PR DESCRIPTION
**Pull request by anishbista60**
## Summary

-  following previous guide , i had a some issue. so, i modified it to run the command from `root`

## Basic example

Include a basic example, screenshots, or links.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Checks

- [ ] Read [Create a Pull Request](https://getdoks.org/docs/contributing/how-to-contribute/#create-a-pull-request)
- [ ] Supports all screen sizes (if relevant)
- [ ] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

### CODE REVIEW

**Comment by anishbista60** [comment]
@achag033 This is small change . while following previous guide and applying mentioned command, It say content directory not found. 
To solve , we should run that command from root.

**Review by achag033 — APPROVED** [review]

**Comment by achag033** [comment]
> @achag033 This is small change . while following previous guide and applying mentioned command, It say content directory not found. To solve , we should run that command from root.

while the change looks good.  branch is missing latest blog content, lets rebase

**Comment by anishbista60** [comment]
@achag033 done. One doubt ! Is it mandatory to make the feature branch stable to main ? I don't think so because everything is going to happen from main and we are adding some changes to it from feature branch, isn't it ?

yeah but current deploy log doesn't show the changes that is not present in feature.
Thank you

**Comment by achag033** [comment]
> @achag033 done. One doubt ! Is it mandatory to make the feature branch stable to main ? I don't think so because everything is going to happen from main and we are adding some changes to it from feature branch, isn't it ?
> 
> yeah but current deploy log doesn't show the changes that is not present in feature. Thank you

Yes ideally we want to check a final thing before merge as it might result in unexpected outcome, so best practice.

**Review by achag033 — APPROVED** [review]

**Comment by anishbista60** [comment]
ok. Sounds good. Thanks alot.✌️

**Pull request merged**
